/* Automatically generated by wasm2c */
#ifndef TEST_H_GENERATED_
#define TEST_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Z_add_instance_t {
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c___indirect_function_table;
} Z_add_instance_t;

void Z_add_init_module(void);
void Z_add_instantiate(Z_add_instance_t*);
void Z_add_free(Z_add_instance_t*);

/* export: 'memory' */
wasm_rt_memory_t* Z_addZ_memory(Z_add_instance_t* instance);

/* export: '__wasm_call_ctors' */
void Z_addZ___wasm_call_ctors(Z_add_instance_t*);

/* export: 'add' */
u32 Z_addZ_add(Z_add_instance_t*, u32, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* Z_addZ___indirect_function_table(Z_add_instance_t* instance);

/* export: '__errno_location' */
u32 Z_addZ___errno_location(Z_add_instance_t*);

/* export: 'fflush' */
u32 Z_addZ_fflush(Z_add_instance_t*, u32);

/* export: 'emscripten_stack_init' */
void Z_addZ_emscripten_stack_init(Z_add_instance_t*);

/* export: 'emscripten_stack_get_free' */
u32 Z_addZ_emscripten_stack_get_free(Z_add_instance_t*);

/* export: 'emscripten_stack_get_base' */
u32 Z_addZ_emscripten_stack_get_base(Z_add_instance_t*);

/* export: 'emscripten_stack_get_end' */
u32 Z_addZ_emscripten_stack_get_end(Z_add_instance_t*);

/* export: 'stackSave' */
u32 Z_addZ_stackSave(Z_add_instance_t*);

/* export: 'stackRestore' */
void Z_addZ_stackRestore(Z_add_instance_t*, u32);

/* export: 'stackAlloc' */
u32 Z_addZ_stackAlloc(Z_add_instance_t*, u32);

/* export: 'emscripten_stack_get_current' */
u32 Z_addZ_emscripten_stack_get_current(Z_add_instance_t*);

#ifdef __cplusplus
}
#endif

#endif  /* TEST_H_GENERATED_ */
